version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    groups:
      all-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 1
