// Regenerates src/data/logos.ts from src/data/boards.json.
//
// The logos are imported statically rather than resolved at runtime because
// Astro's <Image> only optimizes an ImageMetadata object it received through a
// real ESM import. Run this after adding or renaming a board's logo:
//
//   node scripts/gen-logos.mjs
import { readFile, writeFile } from "node:fs/promises";

const boards = JSON.parse(await readFile("src/data/boards.json", "utf8"));
const files = [...new Set(boards.map((b) => b.image))].sort();
const varName = (f) => "img_" + f.replace(/[^a-zA-Z0-9]/g, "_");

const out = [
  "// AUTO-GENERATED by scripts/gen-logos.mjs -- do not edit by hand.",
  'import type { ImageMetadata } from "astro";',
  "",
  ...files.map((f) => `import ${varName(f)} from "../assets/logos/${f}";`),
  "",
  "export const logos: Record<string, ImageMetadata> = {",
  ...files.map((f) => `  "${f}": ${varName(f)},`),
  "};",
  "",
].join("\n");

await writeFile("src/data/logos.ts", out);
console.log(`[gen-logos] wrote ${files.length} logo imports`);
