// AUTO-GENERATED by scripts/gen-logos.mjs -- do not edit by hand.
import type { ImageMetadata } from "astro";

import img_1_png from "../assets/logos/1.png";
import img_10_png from "../assets/logos/10.png";
import img_11_png from "../assets/logos/11.png";
import img_12_png from "../assets/logos/12.png";
import img_13_png from "../assets/logos/13.png";
import img_14_png from "../assets/logos/14.png";
import img_15_png from "../assets/logos/15.png";
import img_16_png from "../assets/logos/16.png";
import img_17_png from "../assets/logos/17.png";
import img_18_png from "../assets/logos/18.png";
import img_19_png from "../assets/logos/19.png";
import img_20_png from "../assets/logos/20.png";
import img_21_png from "../assets/logos/21.png";
import img_22_png from "../assets/logos/22.png";
import img_23_png from "../assets/logos/23.png";
import img_24_png from "../assets/logos/24.png";
import img_26_png from "../assets/logos/26.png";
import img_27_png from "../assets/logos/27.png";
import img_28_png from "../assets/logos/28.png";
import img_29_png from "../assets/logos/29.png";
import img_3_png from "../assets/logos/3.png";
import img_30_png from "../assets/logos/30.png";
import img_31_png from "../assets/logos/31.png";
import img_32_png from "../assets/logos/32.png";
import img_33_png from "../assets/logos/33.png";
import img_34_png from "../assets/logos/34.png";
import img_35_png from "../assets/logos/35.png";
import img_36_png from "../assets/logos/36.png";
import img_37_png from "../assets/logos/37.png";
import img_38_png from "../assets/logos/38.png";
import img_39_png from "../assets/logos/39.png";
import img_4_png from "../assets/logos/4.png";
import img_40_png from "../assets/logos/40.png";
import img_41_png from "../assets/logos/41.png";
import img_42_png from "../assets/logos/42.png";
import img_43_png from "../assets/logos/43.png";
import img_44_png from "../assets/logos/44.png";
import img_45_png from "../assets/logos/45.png";
import img_5_png from "../assets/logos/5.png";
import img_6_png from "../assets/logos/6.png";
import img_7_png from "../assets/logos/7.png";
import img_8_png from "../assets/logos/8.png";
import img_9_png from "../assets/logos/9.png";
import img_arb_jpg from "../assets/logos/arb.jpg";
import img_castle_jpg from "../assets/logos/castle.jpg";
import img_eth_jpg from "../assets/logos/eth.jpg";
import img_winter_jpg from "../assets/logos/winter.jpg";

export const logos: Record<string, ImageMetadata> = {
  "1.png": img_1_png,
  "10.png": img_10_png,
  "11.png": img_11_png,
  "12.png": img_12_png,
  "13.png": img_13_png,
  "14.png": img_14_png,
  "15.png": img_15_png,
  "16.png": img_16_png,
  "17.png": img_17_png,
  "18.png": img_18_png,
  "19.png": img_19_png,
  "20.png": img_20_png,
  "21.png": img_21_png,
  "22.png": img_22_png,
  "23.png": img_23_png,
  "24.png": img_24_png,
  "26.png": img_26_png,
  "27.png": img_27_png,
  "28.png": img_28_png,
  "29.png": img_29_png,
  "3.png": img_3_png,
  "30.png": img_30_png,
  "31.png": img_31_png,
  "32.png": img_32_png,
  "33.png": img_33_png,
  "34.png": img_34_png,
  "35.png": img_35_png,
  "36.png": img_36_png,
  "37.png": img_37_png,
  "38.png": img_38_png,
  "39.png": img_39_png,
  "4.png": img_4_png,
  "40.png": img_40_png,
  "41.png": img_41_png,
  "42.png": img_42_png,
  "43.png": img_43_png,
  "44.png": img_44_png,
  "45.png": img_45_png,
  "5.png": img_5_png,
  "6.png": img_6_png,
  "7.png": img_7_png,
  "8.png": img_8_png,
  "9.png": img_9_png,
  "arb.jpg": img_arb_jpg,
  "castle.jpg": img_castle_jpg,
  "eth.jpg": img_eth_jpg,
  "winter.jpg": img_winter_jpg,
};
